[package]
name = "libtor"
version = "43.5.1+0.4.3.5"
authors = ["Alekos Filini <alekos.filini@gmail.com>"]
license = "MIT"
homepage = "https://github.com/MagicalBitcoin/libtor"
repository = "https://github.com/MagicalBitcoin/libtor"
documentation = "https://docs.rs/libtor/"
description = "Bundle and run Tor inside your own project"
keywords = ["tor", "daemon"]
readme = "README.md"

[dependencies]
libtor-sys = { version = "43.5.1", git = "https://github.com/MagicalBitcoin/libtor-sys", branch = "optional-vendored-ssl" }
libtor-derive = "0.1"
log = "^0.4"

[features]
vendored-openssl = ["libtor-sys/vendored-openssl"]
